include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_returning_null_for_future
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_single_quotes
    - require_trailing_commas
